sudo: required
language: generic
services:
  - docker
  - postgresql
  - redis-server
env:
  global:
    # set SHA to be current sha of git 
    - SHA=$(git rev-parse HEAD)
    # tell google cloud sdk to not use any prompt
    - CLOUD_SDK_CORE_DISABLE_PROMPTS=1
before_install:
  # prepare database for test
  - psql -c 'CREATE TABLE IF NOT EXISTS values (number INTEGER);' -U postgres
  - psql -c "ALTER USER postgres PASSWORD '1234';" -U postgres
  - redis-cli HSET values 5 8
  # prepare test image
  - docker pull kwangdock/docker-fibonacci-complex-api-dev
  - docker pull kwangdock/docker-fibonacci-complex-web-dev
script:
  # test
  - docker run --network=host -t -v /app/node_modules -v $(pwd)/api:/app kwangdock/docker-fibonacci-complex-api-dev npm run test && docker run -e CI=true -t -v /app/node_modules -v $(pwd)/web:/app kwangdock/docker-fibonacci-complex-web-dev npm run test
deploy:
  # deploy on Google K8s Engine
  - provider: script
    on:
      branch: main
    script: bash deploy-gke.sh
  # build and push new image 
  - provider: script
    on:
      branch: main
    script: bash docker-push.sh
