sudo: required
language: generic
services:
  - docker
  - postgresql
  - redis-server
before_install:
  # decrypt service-account.json for google cloud sdk
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # prepare datavase for test
  - psql -c 'CREATE TABLE IF NOT EXISTS values (number INTEGER);' -U postgres
  - psql -c "ALTER USER postgres PASSWORD '1234';" -U postgres
  - redis-cli HSET values 5 8
  # prepare google sdk
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project kube8-practice
  - gcloud config set compute/zone asia-northeast3-a
  - gcloud container clusters get-credentials k8s-fibonacci-complex
  # prepare test image
  - docker pull kwangdock/docker-fibonacci-complex-api-dev
  - docker pull kwangdock/docker-fibonacci-complex-web-dev
script:
  # test
  - docker run --network=host -t -v /app/node_modules -v $(pwd)/api:/app kwangdock/docker-fibonacci-complex-api-dev npm run test && docker run -e CI=true -t -v /app/node_modules -v $(pwd)/web:/app kwangdock/docker-fibonacci-complex-web-dev npm run test
deploy:
  # build and push new image 
  - provider: script
    on:
      branch: main
    script: bash docker-push.sh
  # deploy on Google K8s Engine
  - provider: script
    on:
      branch: main
    script: bash deploy-gke.sh
