services:
  nginx:
    container_name: nginx
    image: kwangdock/docker-fibonacci-complex-nginx
    restart: always
    depends_on:
      - web
      - api
    ports:
      - 80:80
  api:
    container_name: api
    image: kwangdock/docker-fibonacci-complex-api
    expose:
      - 5000
    env_file:
      - .env
  worker:
    container_name: worker
    image: kwangdock/docker-fibonacci-complex-worker
    env_file:
      - .env
  web:
    container_name: web
    image: kwangdock/docker-fibonacci-complex-web
    expose:
      - 3000
