services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 3000:80
  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    expose: 
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
  redis:
    container_name: redis
    image: redis:7
    restart: always
    expose:
      - 6379
  api:
    container_name: api
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    expose:
      - 5000
    environment:
      - REDIS_URL=redis://redis
      - PSQL_URL=postgresql://postgres:1234@postgres:5432/postgres
    volumes:
      - /app/node_modules
      - ./api:/app
  worker:
    container_name: worker
    build: 
      context: ./worker
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_URL=redis://redis
    volumes:
      - /app/node_modules
      - ./worker:/app
  web:
    container_name: web
    build: 
      context: ./web
      dockerfile: Dockerfile.dev
    expose:
      - 3000
    volumes:
      - /app/node_modules
      - ./web:/app
    environment:
      - WDS_SOCKET_PORT=0
