apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hongdae-tk-tls
spec:
  # Secret names are always required.
  secretName: hongdae-tk-tls
  commonName: hongdae.tk
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - hongdae.tk
    - www.hongdae.tk
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-prod
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
